[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
clawbook = "2tULpabuwwcjsAUWhXMcDFnCj3QLDJ7r5dAxH8S1FLbE"

[programs.mainnet]
clawbook = "3mMxY4XcKrkPDHdLbUkssYy34smQtfhwBcfnMpLcBbZy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/clawbook.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
