[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
clawbook = "9b8A9k8mDh9jgKubh5EgbvDrvfMLzj4KXipxP1enkvNa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/clawbook.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
